### ISSUE TITLE
Mac/Chrome Freeze when switching tabs

### ISSUE THREAD

**Issue by ahgold** [BrightCanopy/BrightCanopy.github.io#2] opened 2015-04-13 17:52 UTC
On Mac 10.9.5 and Chrome

Loading Firestorm was fast--less than 30 seconds to reach the login screen.
After entering login information, login was also fast.
As soon as the in-world view appeared and my avi started to rez, the view froze and remained frozen. I was unable to interact with the Firestorm UI or the Windows UI within the browser tab. Clicking the red X had no effect.
I was able to close the browser tab, however, and the rest of my system seemed unaffected.

**Comment by ahgold** [comment] 2015-04-13 17:53
On Mac 10.9.5 and Chrome

Third try...
I am able to switch to other applications than Chrome without trouble, but as soon as I click on another browser tab (this time accidentally), FS & the Windows interface freeze.
Very impressed so far with the quality of the stream, though.

**Comment by ahgold** [comment] 2015-04-13 17:53
On Mac 10.9.5 and Chrome
- Third try... 
- I am able to switch to other applications than Chrome without trouble, but as soon as I click on another browser tab (this time accidentally), FS & the Windows interface freeze.
- Very impressed so far with the quality of the stream, though.

**Comment by ahgold** [comment] 2015-04-13 17:54
Hi,

Ok— tried to test that.

In order to keep the little circles visible if I clicked out of a browser tab, I created a separate Chrome window to open FS in.
- When I was at the Firestorm login screen, I was able to move between the two Chrome _windows_ with no problem.
- After logging in, the little circles were all green, and I was still able to move between Chrome _windows_ with no problem.
- In the Chrome window that did NOT have FS running, I was able to move between _tabs_ with no problem. (little circles all still green)
- So I created a new tab in the Chrome window containing FS. Because I was in a new tab, I could no longer see the green circles. When I tabbed back to the FS window, the screen was completely frozen. (Little circles all still green, but the whole thing was frozen so I don’t think they are indicating the current conditions.)

Hope that helps. Please let me know if there’s anything else I can do.
…

On Apr 13, 2015, at 9:38 AM, Bright Canopy notifications@github.com wrote:  > Great feedback! >  > Those are different results than I've seen, so you've found something. Did > you happen to notice the small circles in the left-hand bottom corner? What > did they do when you were seeing the freeze? >

**Comment by BrightCanopy** [comment] 2015-04-13 18:05
@ahgold Thanks for trying that. I'll ping Frame and bring them into the conversation.

**Comment by BrightCanopy** [comment] 2015-04-14 07:31
More troubleshooting. Could you try again and see what CMD-OPT-j shows you in the error console. The client is a javascript app and hopefully will complain in some useful way when this happens.

**Comment by BrightCanopy** [comment] 2015-04-14 07:57
I may have just reproduced this on Chrome/Linux. When I looked at the error console I saw errors for content blocked by my client, by my ad blocker specifically. (I know... but I have a good heart). I'll ad a reminder to turn off ad blockers to a section of tips on the demo page. We'll do the same in production someday with nice graphics and such. Extra points if we can block people from logging in until they've seen the tutorial.

**Comment by cygnoir** [comment] 2015-04-14 09:40
Hi there. I was able to replicate this on Chrome/Mac, and I wasn't able to access the error console with CMD-OPT-j because the tab is completely frozen. The small circles in the left-hand corner were all filled and green, and my ad blocker was turned off.

**Comment by BrightCanopy** [comment] 2015-04-14 20:11
Thanks, @cygnoir 
Was the working OK until you switched tabs?

**Comment by cygnoir** [comment] 2015-04-14 21:16
Yes, it was working fine ... a bit laggy, but I was 5000+ miles from the server (as it helpfully told me).

**Comment by ahgold** [comment] 2015-04-14 22:19
I turned off my adblocker in Chrome (I disabled it completely and restarted Chrome) and still had the complete frame-freeze when switching tabs.

**Comment by cygnoir** [comment] 2015-04-14 22:31
I encountered the same tab freeze issue with Safari 8.0.5 (Yosemite 10.10.3).

**Comment by BrightCanopy** [comment] 2015-04-14 22:32
@ahgold I think this is definitely a different problem from the adblocker thing. I understand that a native Mac client willl also be available soon. That solves this problem, but, of course, we want to see it work in browser too.

**Comment by BrightCanopy** [comment] 2015-04-15 11:47
Another test. Does clicking on the small network circles make a difference after a freeze? I saw an apparent freeze on Linux after a tab switch which turned out to be related to a network dip on wifi. Just eliminating things.

Meantime, as a workaround to continue testing, please also try running the Frame tab in its own window.

**Comment by ahgold** [comment] 2015-04-15 17:04
Yes! The FS window wakes up again if I click on the network circles. So this is not a crash or disconnect, just a visual tab freeze.
Questions to follow up on:
- If the tab is left frozen for sufficiently long, does SL disconnect? (So far I've stayed tabbed out for up to a minute and have still been able to wake up the tab.)
- When the tab wakes up, does it show all missed activity? (such as IMs received during the freeze)

**Comment by BrightCanopy** [comment] 2015-04-17 03:25
OK. I think we can close this one. We're recovering from network hits. This can improve maybe  by recovering on its own, but this should work for Pre Launch.

**Closed as completed by BrightCanopy** 2015-04-17 03:25 UTC
Labels: bug, Frame
